version: '3'
services:
  server:
    image: nginx:1.15
    volumes:
      - ./bigsite:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/my-site.com.crt:/etc/nginx/my-site.com.crt
      - ./nginx/my-site.com.key:/etc/nginx/my-site.com.key
    ports:
    - "5006:80"
    - "443:443" # Docker open external port 443 and redirect all traffic to internal port 443
